FROM nginx

RUN mkdir /app

WORKDIR /app

RUN mkdir ./build

ADD ./build ./build

RUN rm -rf /etc/nginx.conf.d/default.conf

COPY ./nginx.conf /etc/nginx

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]